name: new_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # <--- FIXED: This is the missing line

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6

  # DOWNGRADED FIREBASE (Stable for Android 33)
  firebase_core: 2.24.2
  cloud_firestore: 4.14.0
  
  intl: ^0.19.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # IMAGES
  assets:
    - assets/images/